### ISSUE TITLE
Supporting pull requests

### ISSUE THREAD

**Issue by MPV** [Amwam/issue-comment-action#1]
Nice action! ❤️ 

Would you be open to adding support for pull requests? 
I.e. triggering on new pull requests, and labeling them based on their description/initial comment.

I tried running it as-is, but can confirm it didn't work out-of-the-box:
```
Run Naturalclar/issue-action@v1.0.0
  with:
    keywords: ["sbt-plugin-update"]
    labels: ["sbt-plugin-update"]
    github-token: ***
keywords: sbt-plugin-update
##[error]No Issue Provided
```

Looks like we're trying to grab the issue only:
https://github.com/Amwam/issue-comment-action/blob/0c4c3930ea93297f7a04b56c2ace8c06a6c7a4a2/src/github.ts#L13

...but the library seems to support getting either PR or issue, if we do something like this:
https://github.com/actions/toolkit/blob/a9175f3/packages/github/src/context.ts#L42-L49

**Comment by Amwam** [comment]
@MPV Hi, sorry for the long reply, I missed this issue completely.

This is totally my mistake, the example in the README was using the wrong action, i've updated it now, but it should have been `Amwam/issue-comment-action@v1.3.1`.

I can confirm this works on pull requests.
